version: '3'

services:
  worker:
    image: alpine:3.13
    command: /log.sh
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://host.docker.internal:601"
    depends_on:
      - syslog
    volumes:
      - ./log.sh:/log.sh

  syslog:
    image: balabit/syslog-ng:latest
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./log:/var/log
    ports:
      - 601:601

